// apps/demo-react/src/CompoundDemo.tsx
import { useDemoI18n } from './demo-language.js';
import { Domternal, useCurrentEditor } from '@domternal/react';
import {
  Bold,
  Italic,
  Underline,
  Strike,
  Heading,
  BulletList,
  OrderedList,
  Link,
  LinkPopover,
  SelectionDecoration,
} from '@domternal/core';

const extensions = [
  Bold,
  Italic,
  Underline,
  Strike,
  Heading,
  BulletList,
  OrderedList,
  Link,
  LinkPopover,
  SelectionDecoration,
];

/** Custom component that pulls the editor from context via useCurrentEditor(). */
function EditorProbe() {
  const { editor } = useCurrentEditor();
  return (
    <div data-testid="editor-probe" data-dm-editor-ui="">
      <span data-testid="has-editor">{editor ? 'yes' : 'no'}</span>
      <button
        type="button"
        data-testid="inject-bold"
        disabled={!editor}
        onMouseDown={(e) => e.preventDefault()}
        onClick={() => editor?.commands.toggleBold()}
      >
        Toggle Bold via inject
      </button>
    </div>
  );
}

/**
 * React demo for the <Domternal> compound component with namespaced
 * subcomponents (Domternal.Content / .Toolbar / .BubbleMenu) and the
 * useCurrentEditor() context hook. Mirrors the Vue CompoundDemo so both
 * wrappers cover the same provide/inject editor-sharing behaviour.
 */
export function CompoundDemo() {
  const i18n = useDemoI18n();
  return (
    <div className="compound-demo" data-demo="compound">
      <h2>Compound Component Demo (&lt;Domternal&gt; with namespaced subcomponents)</h2>

      <Domternal i18n={i18n} extensions={extensions} content="<p>Compound root provides editor via context</p>">
        <Domternal.Toolbar />
        <Domternal.Content />
        <Domternal.BubbleMenu contexts={{ text: ['bold', 'italic', 'underline'] }} />

        <h3>Editor probe (uses useCurrentEditor context)</h3>
        <EditorProbe />
      </Domternal>
    </div>
  );
}

// apps/demo-vue/src/CompoundDemo.vue
<script setup lang="ts">
import type { I18nOptions } from '@domternal/core';
import { h, defineComponent } from 'vue';
import { Domternal, useCurrentEditor } from '@domternal/vue';
import {
  Bold,
  Italic,
  Underline,
  Strike,
  Heading,
  BulletList,
  OrderedList,
  Link,
  LinkPopover,
  SelectionDecoration,
} from '@domternal/core';

defineProps<{ i18n: I18nOptions }>();

const extensions = [
  Bold, Italic, Underline, Strike, Heading, BulletList, OrderedList,
  Link, LinkPopover, SelectionDecoration,
];

// Custom component that uses useCurrentEditor() to inject editor
const EditorProbe = defineComponent({
  name: 'EditorProbe',
  setup() {
    const { editor } = useCurrentEditor();
    return () => h('div', { 'data-testid': 'editor-probe', 'data-dm-editor-ui': '' }, [
      h('span', { 'data-testid': 'has-editor' }, editor.value ? 'yes' : 'no'),
      h('button', {
        'data-testid': 'inject-bold',
        disabled: !editor.value,
        onMousedown: (e: MouseEvent) => e.preventDefault(),
        onClick: () => editor.value?.commands['toggleBold']?.(),
      }, 'Toggle Bold via inject'),
    ]);
  },
});
</script>

<template>
  <div class="compound-demo" data-demo="compound">
    <h2>Compound Component Demo (&lt;Domternal&gt; with namespaced subcomponents)</h2>

    <Domternal :i18n="i18n" :extensions="extensions" content="<p>Compound root provides editor via inject</p>">
      <Domternal.Toolbar />
      <Domternal.Content />
      <Domternal.BubbleMenu :contexts="{ text: ['bold', 'italic', 'underline'] }" />

      <h3>Editor probe (uses useCurrentEditor inject)</h3>
      <EditorProbe />
    </Domternal>
  </div>
</template>
