// apps/demo-react/src/NotionDemo.tsx
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import {
  useEditor,
  useEditorState,
  DomternalBubbleMenu,
  DomternalFloatingMenu,
  DomternalNotionColorPicker,
} from '@domternal/react';
import {
  Bold,
  Italic,
  Underline,
  Strike,
  Code,
  Highlight,
  Subscript,
  Superscript,
  Link,
  LinkPopover,
  ListIndent,
  Heading,
  Blockquote,
  HardBreak,
  HorizontalRule,
  BulletList,
  OrderedList,
  TaskList,
  TextAlign,
  TextColor,
  NotionColorPicker,
  FontSize,
  FontFamily,
  LineHeight,
  SelectionDecoration,
  ClearFormatting,
  Dropcursor,
  UniqueID,
  BlockColor,
  Placeholder,
  inlineStyles,
  getListItemCursorContext,
  type AnyExtension,
} from '@domternal/core';
import { CodeBlockLowlight, createCodeHighlighter } from '@domternal/extension-code-block-lowlight';
import { Image } from '@domternal/extension-image';
import { Details } from '@domternal/extension-details';
import { Table } from '@domternal/extension-table';
import { Emoji, emojis, createEmojiSuggestionRenderer } from '@domternal/extension-emoji';
import { Mention, createMentionSuggestionRenderer } from '@domternal/extension-mention';
import type { MentionItem } from '@domternal/extension-mention';
import {
  BlockHandle,
  BlockContextMenu,
  KeyboardReorder,
  SlashCommand,
  SmartPaste,
} from '@domternal/extension-block-menu';
import type { BlockMatcher, BlockCandidate } from '@domternal/extension-block-menu';
import { TableOfContents, FloatingTocOutline, TableOfContentsBlock } from '@domternal/extension-toc';
import type { IconSet } from '@domternal/core';
import { createLowlight, common } from 'lowlight';
import { NOTION_DEMO_CONTENT } from './notion-demo-content.js';
import {
  parseBubbleIconsParam,
  resolveBubbleIcons,
  type BubbleIconsParam,
} from './bubble-icons-fixtures.js';

const lowlight = createLowlight(common);
const codeHighlighter = createCodeHighlighter(lowlight);

const mockUsers: MentionItem[] = [
  { id: '1', label: 'Alice Johnson' },
  { id: '2', label: 'Bob Smith' },
  { id: '3', label: 'Charlie Brown' },
  { id: '4', label: 'Diana Prince' },
  { id: '5', label: 'Eve Adams' },
];

/**
 * Parents whose direct paragraph children should NOT surface their own
 * drag handle - the container itself is the meaningful drag unit. Module
 * scope so the matcher's `test` callback doesn't allocate per candidate.
 */
const PARAGRAPH_EXCLUSION_PARENTS = new Set([
  'blockquote', 'tableCell', 'tableHeader', 'tableRow', 'details', 'detailsContent',
]);

/**
 * Toast display durations (ms). Error toast lingers ~50% longer because it
 * carries diagnostic copy users may want to read; success is shorter to
 * stay out of the way.
 */
const TOAST_MS = { success: 1800, error: 2600 } as const;

const buildExtensions = (scrollParent: Element | null): AnyExtension[] => [
  Italic, Bold, Underline, Strike, Code, Highlight, Subscript, Superscript, Link,
  Heading, Blockquote, CodeBlockLowlight.configure({ lowlight }), HardBreak, HorizontalRule,
  BulletList, OrderedList, TaskList,
  TextAlign, TextColor, FontSize, FontFamily, LineHeight,
  NotionColorPicker,
  Table,
  Details,
  Image,
  Emoji.configure({
    emojis,
    enableEmoticons: true,
    toolbar: false,
    suggestion: { render: createEmojiSuggestionRenderer() },
  }),
  Mention.configure({
    suggestion: {
      char: '@',
      name: 'user',
      items: ({ query }: { query: string }) =>
        mockUsers.filter((u) => u.label.toLowerCase().includes(query.toLowerCase())),
      render: createMentionSuggestionRenderer(),
      minQueryLength: 0,
      invalidNodes: ['codeBlock'],
    },
  }),
  LinkPopover, SelectionDecoration, ClearFormatting,
  // Native PM dropcursor; BlockHandle hides it during a handle drag so
  // only the custom `.dm-block-drop-indicator` shows. Kept loaded for
  // non-handle drops (text selection, external file drops).
  Dropcursor,
  // Registered after the list extensions so their in-item Tab/Shift-Tab
  // keymaps keep priority inside list items.
  ListIndent,
  UniqueID,
  BlockColor,
  // `paragraphInsideContainer` keeps containers (blockquote / tableCell /
  // details) as one drag unit. Paragraphs nested in listItem are NOT
  // covered because they were Tab-indented as separate logical blocks.
  BlockHandle.configure({
    nested: {
      allowedNodes: [
        'listItem', 'taskItem',
        'heading', 'paragraph', 'codeBlock', 'blockquote', 'horizontalRule',
      ],
      matchers: [
        {
          name: 'paragraphInsideContainer',
          test: ({ block, container }: BlockCandidate) =>
            block.type.name === 'paragraph'
              && container !== null
              && PARAGRAPH_EXCLUSION_PARENTS.has(container.type.name)
              ? 'reject'
              : 'allow',
        } satisfies BlockMatcher,
      ],
    },
  }),
  BlockContextMenu,
  KeyboardReorder,
  SlashCommand,
  SmartPaste,
  TableOfContents,
  FloatingTocOutline.configure({ activeScrollParent: scrollParent }),
  TableOfContentsBlock,
  // Empty paragraphs get the slash hint; other empty blocks stay quiet so
  // the hint isn't repeated on every block.
  Placeholder.configure({
    placeholder: ({ node }) =>
      node.type.name === 'paragraph' ? "Press '/' for commands" : '',
  }),
];

interface Toast {
  id: number;
  message: string;
  kind: 'success' | 'error';
}

const getStyledHtml = (html: string): string => {
  return inlineStyles(html, { codeHighlighter, tableColumnWidths: 'pixel' });
};

export interface NotionDemoProps {
  /** Cap the page wrapper height and scroll its content internally. Adds
   * `notion-page--scrollable` and wires `activeScrollParent` so the TOC
   * scroll-spy follows the host scroll instead of the window. */
  scrollable?: boolean;
}

/**
 * Notion-style demo: no toolbar, floating menu on empty lines is the primary
 * block-insert UI, bubble menu for text formatting on selection. Mirrors
 * `apps/demo-angular/src/app/notion-demo/notion-demo.component.ts`.
 */
export function NotionDemo({ scrollable = false }: NotionDemoProps): ReactNode {
  // Capture the page wrapper element via a state-based ref. In scrollable
  // mode the TOC needs this element to wire `activeScrollParent`; React
  // can only hand it to us after first paint, so the editor recreates
  // once when the ref resolves. Non-scrollable mode never reads it.
  const [pageEl, setPageEl] = useState<HTMLDivElement | null>(null);

  const extensions = useMemo<AnyExtension[]>(
    () => buildExtensions(scrollable ? pageEl : null),
    [scrollable, pageEl],
  );

  const { editor, editorRef } = useEditor({
    extensions,
    content: NOTION_DEMO_CONTENT,
  });

  const { htmlContent } = useEditorState(editor);

  const [toasts, setToasts] = useState<Toast[]>([]);

  // E2E fixture for bubble menu icons override.
  const [bubbleIcons, setBubbleIcons] = useState<IconSet | undefined>(() =>
    resolveBubbleIcons(parseBubbleIconsParam()),
  );

  useEffect(() => {
    const w = window as unknown as Record<string, unknown>;
    w['__DEMO_SET_BUBBLE_ICONS__'] = (key: BubbleIconsParam | null): void => {
      setBubbleIcons(resolveBubbleIcons(key));
    };
    return () => { w['__DEMO_SET_BUBBLE_ICONS__'] = undefined; };
  }, []);

  // Expose editor + cursor-context util on window for e2e, and wire the
  // copy-link toast listeners. Cleanup detaches everything; StrictMode dev
  // double-mount is benign because the second mount re-sets the same editor.
  useEffect(() => {
    if (!editor) return;

    const w = window as unknown as Record<string, unknown>;
    w['__DEMO_EDITOR__'] = editor;
    w['__DOMTERNAL_LIST_CTX__'] = getListItemCursorContext;

    const host = editor.view.dom.closest<HTMLElement>('.dm-editor');
    const controller = new AbortController();
    const { signal } = controller;

    const pushToast = (message: string, kind: Toast['kind']): void => {
      const id = Date.now() + Math.random();
      setToasts((current) => [...current, { id, message, kind }]);
      setTimeout(() => {
        setToasts((current) => current.filter((t) => t.id !== id));
      }, TOAST_MS[kind]);
    };

    host?.addEventListener('dm:copy-link-success', () => {
      pushToast('Link copied', 'success');
    }, { signal });
    host?.addEventListener('dm:copy-link-error', () => {
      pushToast('Failed to copy link', 'error');
    }, { signal });

    return () => {
      controller.abort();
      // Only clear when our editor is still the one on the window. StrictMode
      // dev double-mount can land the second mount's assignment BEFORE the
      // first mount's cleanup; an unconditional clear would leave the window
      // pointing at undefined while the live editor is fine.
      if (w['__DEMO_EDITOR__'] === editor) {
        w['__DEMO_EDITOR__'] = undefined;
        w['__DOMTERNAL_LIST_CTX__'] = undefined;
      }
    };
  }, [editor]);

  return (
    <>
      <div className="app-notion-demo">
        <div
          ref={setPageEl}
          className={scrollable ? 'notion-page notion-page--scrollable' : 'notion-page'}
        >
          <div className="dm-editor dm-notion-mode">
            <div ref={editorRef} />
          </div>

          {editor && (
            <>
              <DomternalBubbleMenu editor={editor} icons={bubbleIcons} />
              <DomternalFloatingMenu editor={editor} requireExplicitTrigger />
              <DomternalNotionColorPicker editor={editor} />
            </>
          )}
        </div>
      </div>

      <h3>HTML Output</h3>
      <pre className="output">{htmlContent}</pre>

      <h3>Styled HTML Output</h3>
      <pre className="output-styled">{htmlContent ? getStyledHtml(htmlContent) : ''}</pre>

      {toasts.length > 0 && createPortal(
        <>
          {toasts.map((t) => (
            <div
              key={t.id}
              role={t.kind === 'success' ? 'status' : 'alert'}
              className={`notion-demo-toast${t.kind === 'error' ? ' notion-demo-toast--error' : ''}`}
            >
              {t.message}
            </div>
          ))}
        </>,
        document.body,
      )}
    </>
  );
}

// apps/demo-angular/src/app/notion-demo/notion-demo.component.ts
import { Component, ChangeDetectionStrategy, ElementRef, OnDestroy, computed, input, signal, viewChild } from '@angular/core';
import {
  DomternalEditorComponent,
  DomternalBubbleMenuComponent,
  DomternalFloatingMenuComponent,
  DomternalNotionColorPickerComponent,
} from '@domternal/angular';
import {
  Bold,
  Italic,
  Underline,
  Strike,
  Code,
  Highlight,
  Subscript,
  Superscript,
  Link,
  LinkPopover,
  ListIndent,
  Heading,
  Blockquote,
  HardBreak,
  HorizontalRule,
  BulletList,
  OrderedList,
  TaskList,
  TextAlign,
  TextColor,
  NotionColorPicker,
  FontSize,
  FontFamily,
  LineHeight,
  SelectionDecoration,
  ClearFormatting,
  Dropcursor,
  UniqueID,
  BlockColor,
  Placeholder,
  Editor,
  inlineStyles,
  getListItemCursorContext,
  type AnyExtension,
} from '@domternal/core';
import { CodeBlockLowlight, createCodeHighlighter } from '@domternal/extension-code-block-lowlight';
import { Image } from '@domternal/extension-image';
import { Details } from '@domternal/extension-details';
import { Table } from '@domternal/extension-table';
import { Emoji, emojis, createEmojiSuggestionRenderer } from '@domternal/extension-emoji';
import { Mention, createMentionSuggestionRenderer } from '@domternal/extension-mention';
import {
  BlockHandle,
  BlockContextMenu,
  KeyboardReorder,
  SlashCommand,
  SmartPaste,
} from '@domternal/extension-block-menu';
import type { BlockMatcher, BlockCandidate } from '@domternal/extension-block-menu';
import { TableOfContents, FloatingTocOutline, TableOfContentsBlock } from '@domternal/extension-toc';
import { NOTION_DEMO_CONTENT } from './notion-demo-content.js';

/**
 * Parents whose direct paragraph children should NOT surface their own
 * drag handle - the container itself is the meaningful drag unit. Hoisted
 * to module scope so the rule's `evaluate` callback doesn't allocate a
 * new Set per candidate node during hover walks.
 */
const PARAGRAPH_EXCLUSION_PARENTS = new Set([
  'blockquote', 'tableCell', 'tableHeader', 'tableRow', 'details', 'detailsContent',
]);
import type { MentionItem } from '@domternal/extension-mention';
import type { IconSet } from '@domternal/core';
import { createLowlight, common } from 'lowlight';
import {
  parseBubbleIconsParam,
  resolveBubbleIcons,
  type BubbleIconsParam,
} from '../bubble-icons-fixtures.js';

const lowlight = createLowlight(common);
const codeHighlighter = createCodeHighlighter(lowlight);

const mockUsers: MentionItem[] = [
  { id: '1', label: 'Alice Johnson' },
  { id: '2', label: 'Bob Smith' },
  { id: '3', label: 'Charlie Brown' },
  { id: '4', label: 'Diana Prince' },
  { id: '5', label: 'Eve Adams' },
];

/**
 * Notion-style demo: no toolbar, floating menu on empty lines is the primary
 * block-insert UI, bubble menu for text formatting on selection.
 */
@Component({
  selector: 'app-notion-demo',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    DomternalEditorComponent,
    DomternalBubbleMenuComponent,
    DomternalFloatingMenuComponent,
    DomternalNotionColorPickerComponent,
  ],
  templateUrl: './notion-demo.component.html',
  styleUrls: ['./notion-demo.component.scss'],
})
export class NotionDemoComponent implements OnDestroy {
  /**
   * Toast display durations (ms). Error toast lingers ~50% longer because it
   * carries diagnostic copy users may want to read; success is shorter to
   * stay out of the way.
   */
  private static readonly TOAST_MS = { success: 1800, error: 2600 };

  /**
   * Cap the page wrapper height and scroll its content internally. Adds
   * `notion-page--scrollable` and wires `activeScrollParent` so the TOC
   * scroll-spy follows the host scroll instead of the window.
   */
  readonly scrollable = input(false);

  /**
   * Reference to the `.notion-page` wrapper. Resolved after first render;
   * the `extensions` computed below picks it up so the editor recreates
   * with the wired `activeScrollParent` when this signal resolves.
   */
  readonly pageElRef = viewChild<ElementRef<HTMLDivElement>>('pageEl');

  readonly extensions = computed<AnyExtension[]>(() => {
    const sp = this.scrollable() ? this.pageElRef()?.nativeElement ?? null : null;
    return NotionDemoComponent.buildExtensions(sp);
  });

  private static buildExtensions(scrollParent: Element | null): AnyExtension[] {
    return [
      Italic, Bold, Underline, Strike, Code, Highlight, Subscript, Superscript, Link,
      Heading, Blockquote, CodeBlockLowlight.configure({ lowlight }), HardBreak, HorizontalRule,
      BulletList, OrderedList, TaskList,
      TextAlign, TextColor, FontSize, FontFamily, LineHeight,
      NotionColorPicker,
      Table,
      Details,
      Image,
      Emoji.configure({
        emojis,
        enableEmoticons: true,
        toolbar: false,
        suggestion: { render: createEmojiSuggestionRenderer() },
      }),
      Mention.configure({
        suggestion: {
          char: '@',
          name: 'user',
          items: ({ query }: { query: string }) =>
            mockUsers.filter((u) => u.label.toLowerCase().includes(query.toLowerCase())),
          render: createMentionSuggestionRenderer(),
          minQueryLength: 0,
          invalidNodes: ['codeBlock'],
        },
      }),
      LinkPopover, SelectionDecoration, ClearFormatting,
      // Native PM dropcursor; BlockHandle hides it during a handle drag so
      // only the custom `.dm-block-drop-indicator` shows. Kept loaded for
      // non-handle drops (text selection, external file drops).
      Dropcursor,
      // Registered after the list extensions so their in-item Tab/Shift-Tab
      // keymaps keep priority inside list items.
      ListIndent,
      UniqueID,
      BlockColor,
      // `paragraphInsideContainer` keeps containers (blockquote / tableCell /
      // details) as one drag unit. Paragraphs nested in listItem are NOT
      // covered because they were Tab-indented as separate logical blocks.
      BlockHandle.configure({
        nested: {
          allowedNodes: [
            'listItem', 'taskItem',
            'heading', 'paragraph', 'codeBlock', 'blockquote', 'horizontalRule',
          ],
          matchers: [
            {
              name: 'paragraphInsideContainer',
              test: ({ block, container }: BlockCandidate) =>
                block.type.name === 'paragraph'
                  && container !== null
                  && PARAGRAPH_EXCLUSION_PARENTS.has(container.type.name)
                  ? 'reject'
                  : 'allow',
            } satisfies BlockMatcher,
          ],
        },
      }),
      BlockContextMenu,
      KeyboardReorder,
      SlashCommand,
      SmartPaste,
      TableOfContents,
      FloatingTocOutline.configure({ activeScrollParent: scrollParent }),
      TableOfContentsBlock,
      // Empty paragraphs get the slash hint; other empty blocks stay quiet so
      // the hint isn't repeated on every block.
      Placeholder.configure({
        placeholder: ({ node }) =>
          node.type.name === 'paragraph' ? "Press '/' for commands" : '',
      }),
    ];
  }

  editorContent = NOTION_DEMO_CONTENT;
  editor = signal<Editor | null>(null);

  // E2E fixture for bubble menu icons override.
  readonly bubbleIcons = signal<IconSet | undefined>(resolveBubbleIcons(parseBubbleIconsParam()));

  constructor() {
    const w = window as unknown as Record<string, unknown>;
    w['__DEMO_SET_BUBBLE_ICONS__'] = (key: BubbleIconsParam | null): void => {
      this.bubbleIcons.set(resolveBubbleIcons(key));
    };
  }

  // Tracked so `ngOnDestroy` and subsequent `onEditorCreated` calls can
  // remove listeners before adding new ones. Without this, repeatedly
  // mounting the component (HMR / route re-entry) would accumulate
  // listeners on the same `.dm-editor` DOM node.
  private copyLinkHost: HTMLElement | null = null;
  private copyLinkSuccessListener: ((event: Event) => void) | null = null;
  private copyLinkErrorListener: ((event: Event) => void) | null = null;

  onEditorCreated(editor: Editor): void {
    this.editor.set(editor);
    // Expose for E2E + playing around in devtools.
    (window as unknown as Record<string, unknown>)['__DEMO_EDITOR__'] = editor;
    // Expose getListItemCursorContext for E2E coverage of the pure
    // utility - lets tests verify the util resolves correctly when run
    // against the built dist (not just the unit-test source path).
    (window as unknown as Record<string, unknown>)['__DOMTERNAL_LIST_CTX__'] = getListItemCursorContext;

    // Tear down any previously-attached listeners before wiring new ones -
    // protects against leaking listeners when the editor is recreated
    // (HMR, re-entering the route, etc.).
    this.removeCopyLinkListeners();

    // Surface toasts when "Copy link to block" succeeds or fails. Host apps
    // own this UX: BlockContextMenu only emits `dm:copy-link-success` (on
    // actual success) and `dm:copy-link-error` (on clipboard failure).
    const host = editor.view.dom.closest<HTMLElement>('.dm-editor');
    if (!host) return;
    this.copyLinkHost = host;

    this.copyLinkSuccessListener = (): void => {
      this.showToast('Link copied', 'status', 'notion-demo-toast', NotionDemoComponent.TOAST_MS.success);
    };
    this.copyLinkErrorListener = (): void => {
      this.showToast('Failed to copy link', 'alert', 'notion-demo-toast notion-demo-toast--error', NotionDemoComponent.TOAST_MS.error);
    };
    host.addEventListener('dm:copy-link-success', this.copyLinkSuccessListener);
    host.addEventListener('dm:copy-link-error', this.copyLinkErrorListener);
  }

  /** Inline-style the live HTML output for the "Styled HTML" pane. */
  getStyledHtml(html: string): string {
    return inlineStyles(html, { codeHighlighter, tableColumnWidths: 'pixel' });
  }

  ngOnDestroy(): void {
    this.removeCopyLinkListeners();
    this.copyLinkHost = null;
    const w = window as unknown as Record<string, unknown>;
    w['__DEMO_SET_BUBBLE_ICONS__'] = undefined;
  }

  private removeCopyLinkListeners(): void {
    if (!this.copyLinkHost) return;
    if (this.copyLinkSuccessListener) {
      this.copyLinkHost.removeEventListener('dm:copy-link-success', this.copyLinkSuccessListener);
      this.copyLinkSuccessListener = null;
    }
    if (this.copyLinkErrorListener) {
      this.copyLinkHost.removeEventListener('dm:copy-link-error', this.copyLinkErrorListener);
      this.copyLinkErrorListener = null;
    }
  }

  private showToast(message: string, role: 'status' | 'alert', className: string, durationMs: number): void {
    const toast = document.createElement('div');
    toast.className = className;
    toast.textContent = message;
    toast.setAttribute('role', role);
    document.body.appendChild(toast);
    setTimeout(() => toast.remove(), durationMs);
  }
}

<div class="notion-page">
  <domternal-editor
    #ec
    class="dm-notion-mode"
    [extensions]="extensions"
    [content]="editorContent"
    (editorCreated)="onEditorCreated($event)"
  />

  @if (editor(); as ed) {
    <domternal-bubble-menu
      [editor]="ed"
      [contexts]="{
        text: ['bold', 'italic', 'underline', 'strike', 'code', '|', 'link', '|', 'textAlign'],
      }"
    />
    <domternal-floating-menu [editor]="ed" [requireExplicitTrigger]="true" />
    <domternal-notion-color-picker [editor]="ed" />
  }
</div>

<h3>HTML Output</h3>
<pre class="output">{{ ec.htmlContent() }}</pre>

<h3>Styled HTML Output</h3>
<pre class="output-styled">{{ getStyledHtml(ec.htmlContent()) }}</pre>
